jenkoian/hacktoberfest-checker

README.md
css/main.css
index.js
views/index.hbs

Context messages are slightly smaller than the "x / 4 pull requests submitted" string.

Added contextual message

---

.gitignore
bower.json
css/main.css
package.json
views/index.hbs

* Fix some text
* Tidying the CSS
* Improve fonts for non-Mac nerds
* Removes unneeded `<br>` tag
* postinstall explicitly calls Node.js for Windows types
* .gitignore has Visual Studio Node.js project added

Quick fixes

---

index.js
public/js/script.js
views/index.hbs
views/partials/prs.hbs

I saw your todo "Fix ability to link to users that ajax fix above broke (e.g. http://localhost:5000/?username=jenkoian)" and I think this fixes it.

Make get parameters work

---

index.js
public/css/main.css
views/partials/prs.hbs

- Adds PR status
- Switches from using Github event api to Github search api
- Adds avatar

switches github event api to search api and adds avatar

---

LICENSE
README.md

Update license and year

---

views/index.hbs

Button and title similar

---

public/css/main.css
views/index.hbs

Some style fixes which removed vertical scrollbar

Vertical scrollbar fix

---

Dockerfile
README.md

I added a dockerfile, so it's possbile to create a docker image and run the app within a docker container. So it's not necessary to have node installed.

Add dockerfile to run app within docker

---

public/css/main.css

Button normal:
Button with hover:

Hover in button check

---

index.js

Fixes https://github.com/jenkoian/hacktoberfest-checker/issues/48

PRs marked invalid don't count

---

public/humans.txt
public/js/script.js

slight grammatical fix

---

README.md

ln 3: "to see how close you are ..." sounds a little better than "for seeing how close you are"
ln 14: Stating "you can get involved" flows a little better than "get involved" which in this context seems like it doesn't fit as well. Also sounds more inviting.

Minor wording changes

---

public/css/main.css
views/index.hbs
views/partials/prs.hbs

Added social media buttons for when a user is searched.

#52 added share buttons

---

README.md

I've added a section in the readme for testing and how to use and install Jest

add testing section to readme

---

package.json

Fix indentation

---

views/index.hbs

when we open a new page in new tab, there is more chance of visitors staying in the website . so , i changed target to blank which opens "fork me on github" on new tab .

opens "Fork me on github" on new tab

---

views/partials/prs.hbs
yarn.lock

Updated my local version of yarn which seems to have updated the lock file too. Trusting this isn't an issue..

Add url of app to tweet

---

README.md

Adjust copyright symbol

---

controllers/index.js

Fetch pull request for October 2017 instead of 2016

changed query to 2017

---

public/css/main.css

Sans-serif font

---

views/index.hbs

Looks like this now. Fixes #110

Fixed searchbar width on mobile

---

.eslintrc.js
controllers/index.js
index.js
package.json
public/js/main.js

added basic eslint
run with `npm run eslint`
fix basic issues with `npm run eslint-fix`
picked single quotes (hence the .js updates) but this can be changed in the .eslintrc.js

Added ESlint 

---

public/js/main.js

In the spirit of Hacktoberfest, here is a grammatical update for the API errors in main.js.

Grammatical Fix for main.js

---

controllers/index.js

Removed an unnecessary space in the statement.
- It 's    ->    It's

Fixed typo in statements.

---

LICENSE

This is also what it says at the bottom of your readme.md file

Update LICENSE just to be on the safe side

---

controllers/index.js

This PR will modify some of the statements to make their tone a little more positive; just a minor nitpick. I think a lot of people tend to have negative connotations with a period, so just tweaked that and tried to make it a little more motivational.
Feel free to merge if you're cool with the changes, or reject if you think they're unnecessary!

Modify tone of certain message statements

---

views/layouts/main.hbs

Add meta theme-color

---

README.md

- https://github.com/jenkoian/hacktoberfest-checker/issues/155
- Prefixed $ before commands in readme

prefixed with $ for commands

---

index.js

Add back github authentication.

---

public/css/main.css
views/layouts/main.hbs
views/partials/footer.hbs

Footer should be down, so it's better.
Demo:

Make footer position to bottom of page

---

views/partials/footer.hbs

For better display on small screen (iPhone 5 example).
| Before | After 
| - | - 
| ![image](https://user-images.githubusercontent.com/4408379/31174085-df56160a-a912-11e7-9b1a-2d4f8b83413a.png) | ![image](https://user-images.githubusercontent.com/4408379/31174090-e3066660-a912-11e7-8ca0-9fc8b0d168fa.png)

Add small horizontal padding to footer

---

controllers/index.js

Code style fix

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Added an issue and pull request template in .github/ following https://github.com/blog/2111-issue-and-pull-request-templates

Add issue template and improve pull request template

---

controllers/index.js
public/js/main.js

fix routing

---

.gitignore

Changes: Add NPM lock files to .gitignore

Add lock files to .gitignore

---

.env.example
README.md

Changes: A tiny fix so that there is no confusion with Hacktoberfest, so there should be "Hacktober Checker".

Update description in link to generate GitHub token

---

index.js
package.json
views/layouts/main.hbs

Changes: Add external dependencies (CSS and JS) via npm.

Install external dependencies via npm

---

controllers/index.js
package.json
views/partials/prs.hbs
yarn.lock

Fixes issue #[ #184 ]
Changes: [PR created date was published.]
Previously

Added a PR created date

---

CONTRIBUTING.md

Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]

add contributing steps

---

controllers/index.js
public/css/main.css
public/js/main.js
views/partials/prs.hbs

Image node UI improved during image loads

---

public/js/main.js
views/layouts/main.hbs
views/partials/prs.hbs

First steps for issues #179 
Changes: Tweet button added
Screenshots for the change: http://take.ms/91Db7 http://take.ms/qnX2N

feat: add twitter share button

---

controllers/index.js

Fix issue with repos with pull in the name.

---

public/css/main.css
public/js/main.js
views/layouts/main.hbs
views/partials/prs.hbs

Fixes issue #200 
Changes: Facebook share button added 
Screenshots for the change: http://take.ms/b8oQh  http://take.ms/eAmkj

feat: add facebook share button

---

public/css/main.css

Changes the username input's outline / glow effect to fit the aesthetic theme of the page.
Changes: 
- Transition box-shadow property on input
- Box shadow property on input:focus
Before:
After:

Change input outline to fit theme.

---

public/css/main.css
views/layouts/main.hbs

Fixes issue #220 
I added "position:fixed" style to starts so it stays in place while scrolling.

Fix Background issue while scrolling

---

views/partials/prs.hbs

Added alt text to user image to resolve Axe audit warning.
Fixes issue #226

Added alt text to user image. [ Issue: #226 ]

---

.eslintrc.js
controllers/index.js
index.js
public/js/.eslintrc.js
public/js/main.js

Changes: I noticed that there was some inconsistent spacing with tabs and some spaces being 2 or 4 so i set eslint to do consistent spacing

use eslint to set code spacing

---

controllers/index.js
package-lock.json

Fixes issue #254.
Changes: Changed the promise chain slightly, due to the annoying way the API works. So there are a few extra `Promise.resolve` calls in the original code as well as the obvious new code.

Page through search data

---

views/index.hbs
views/partials/prs.hbs

**Changes:** This updates spacing to be on the bottom of each element for consistency. This practice is especially useful for margins, as it helps for a more predictable collapse. Ideally the UI wont look much different, just a little code cleanup here :)

move spacing to bottom of container elements

---

views/layouts/main.hbs

Worried that people may just use this site without registering so add a banner to remind them.

Add banner to remind people to register

---

controllers/index.js
views/index.hbs

Now on the homepage we have a countdown with the days remaining in the
month. The message changes once we get closer to the end!
Changes: Added the days remaining countdown

Added Days Remaining Countdown

---

views/index.hbs

Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]

fix: add aria-label for A11y purpose

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes issue #304 
Changes: I just updating Pull Request Template file into format that references on the issue.
Screenshots for the change: 
If there is message still need to change, please let me know

Updating pull PULL_REQUEST_TEMPLATE.md from issue #165

---

.dockerignore
Dockerfile
README.md
docker-compose.yml

Changes: 
- **Added the .dockerignore:** when you in the Dockerfile do the `COPY ./APP` command it will copy all the file, also the .git folder, that are useless and so much big 
- **Added the docker-compose:** for a local usage or also to not use a docker command I had also add the docker-compose configuration
- **Fix the Dockerfile:** the application need node > 8.x but in the dockerfile is used the node 6-alpine

Better Docker configuration 

---

CONTRIBUTING.md
index.js
public/humans.txt

First off, hello! Thanks for submitting a PR. We love/welcome PRs (especially if it's your first). Have any questions? Read [this section in CONTRIBUTING.md](https://github.com/jenkoian/hacktoberfest-checker/blob/master/CONTRIBUTING.md#contribute) 
**Ticket**: #

improved formatting in CONTRIBUTING.md, index.js

---

public/css/main.css

Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]

fix: Change color for the .orange CSS class for A11y purpose (contrast)

---

views/partials/prs.hbs

First off, hello! Thanks for submitting a PR. We love/welcome PRs (especially if it's your first). Have any questions? Read [this section in CONTRIBUTING.md](https://github.com/jenkoian/hacktoberfest-checker/blob/master/CONTRIBUTING.md#contribute) 
**Ticket**: #323 
Fixed tweet issue that was rendering empty tweet box.
None

Fixed twitter sharing button

---

CONTRIBUTING.md

First off, hello! Thanks for submitting a PR. We love/welcome PRs (especially if it's your first). Have any questions? Read [this section in CONTRIBUTING.md](https://github.com/jenkoian/hacktoberfest-checker/blob/master/CONTRIBUTING.md#contribute) 
**Ticket**: # 
#013startingoutheretyvm
Better formatting and fixed grammar mistakes
Better formatting so it can be easily interpreted from those that are starting out with open - source (like me)

Better formatting/fixed grammar mistake

---

.gitignore
package-lock.json
package.json
src/pages/User/components/PullRequests/IssuesLink.js

- Changed react-scripts to be set on 3.0.1 (fixes forEach error)
- Fixed issue text colours

Minor fixes to 2019 update

---

CONTRIBUTING.md

some changes

---

src/pages/User/components/PullRequests/MeLinkInfo.js

This PR is modifying the "This is Me" button so that it gives feedback after being clicked and it shows the right information to the user.

Dynamic Me Link

---

package-lock.json
package.json
public/humans.txt
public/index.html
src/components/Footer.js
src/index.css
src/pages/User/components/PullRequests/ShareButtons.js
src/style.css

fixes https://github.com/jenkoian/hacktoberfest-checker/issues/414

Using the font awesome react component instead of loading all icons from the CDN

---

.env.example
api/index.js
package.json

I've added gzip compression to the backend of the app as asked on the issue

Adding gzip compression to the server-side

---

api/index.js
public/index.html

Hoping this will avoid having to add a cookie banner.
https://support.google.com/analytics/answer/6366371?hl=en

Anonymise GA data

---

src/index.css
src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js

fix:improve styles to display the status of PR

---

api/controllers/pr/errors.js
api/controllers/pr/findPrs/getNextPage.js
api/controllers/pr/findPrs/index.js
api/controllers/pr/findPrs/loadPrs.js
api/controllers/pr/index.js
api/controllers/pr/logCallsRemaining.js
api/index.js
api/setupHelpers/setupErrorHandling.js
api/setupHelpers/setupGithubApi.js
package-lock.json
package.json
src/components/GithubCorner/index.js
src/components/PageWrapper.js
src/components/UsernameForm/UsernameInput.js
src/components/UsernameForm/index.js
src/pages/Faq/data.js
src/pages/Faq/index.js
src/pages/User/components/PullRequests/ErrorText.js
src/pages/User/components/PullRequests/MeLinkInfo.js
src/pages/User/components/PullRequests/PullRequest/MergeStatus.js
src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js
src/pages/User/components/PullRequests/PullRequest/index.js
src/pages/User/components/PullRequests/ShareButtons.js
src/pages/User/components/PullRequests/UserInfo/PullRequestCount.js
src/pages/User/components/PullRequests/UserInfo/ResultMessage/getResultMessage.js
src/pages/User/components/PullRequests/UserInfo/ResultMessage/index.js
src/pages/User/components/PullRequests/UserInfo/UserImage.js
src/pages/User/components/PullRequests/UserInfo/index.js
src/pages/User/components/PullRequests/index.js
src/pages/User/index.js

Runs prettier-fix to update to latest standards as well, appears to be
mostly brackets around arguments for arrow functions.

Update to latest version of prettier.

---

package-lock.json

`npm audit fix` didn't seem to do anything so had to delete lock file
and node_modules and reinstall but this has seemed to have done the
trick.

Fix low vulnerabilities.

---

src/components/RegisterReminder.js

Used fontawesome for info icon at top of page

---

package-lock.json
package.json

https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.8.13

Update tailwind to 1.8.13

---

src/pages/User/components/PullRequests/hooks/useFetchPullRequests.js
src/pages/User/components/PullRequests/index.js

I know I'm pretty late to the party but as part of the HacktoberFest 2020, I've converted this class component to function component. I've also separated out fetching pull requests logic to its own hook.
Kindly review this PR and let me know if need to make any changes

chore: Refactor PullRequests class component to function component

---

api/controllers/pr/index.js

Both PRs and MRs are sorted by date and the most recent ones will come first.
Closes #576

Added support for smarter combination of PRs and MRs.

---

README.md

fix: update shields

---

src/components/Footer.js

Invisible links issue solved

---

src/index.css

Run tailwind-gen to get latest style.css changes

---

src/index.css
src/style.css

Hey @jenkoian! A duplicate block of CSS has been removed in style.css. Duplicate blocks (Lines 46-64)

Fix : Duplicate block of css in style.css

---

src/components/UsernameForm/TimeMessage/getTimeMessage.js
src/components/UsernameForm/TimeMessage/index.js

show live remaining time
