README.md, index.js, package.json
Implemented with `memory-cache`
=> Reduced risk of reaching rate limit on github API

Dockerfile
There are a lots of way to improve the node usage with Docker, one of them is to cache the node_modules folder so that npm install runs only if the package.json changes
see 
[https://nodesource.com/blog/8-protips-to-start-killing-it-when-dockerizing-node-js/#protip3startcachingnode_modules](https://nodesource.com/blog/8-protips-to-start-killing-it-when-dockerizing-node-js/#protip3startcachingnode_modules) for more details
=> Improve Dockerfile to cache node_modules

public/js/script.js
After discussing some refactoring in #16 before adding tests I've decided to start from the front end that it's easier to de-couple.
I went for plain ol' JavaScript, no ES6/TypeScript so it will be easier for other developer to understand what's going on and there is no need to know ES6/TS
If/when we're all happy with this refactor I can start to add tests!
=> Refactor the front end, components should be easier to test now

index.js, views/partials/issues.hbs
As discussed in #51 I've added the language to the repo list
now the first limitation is: the library used to interact with GitHub when calling the repo info is returning just one language (probably the most used) instead the API exposed by github returns all the languages used in the repo [https://developer.github.com/v3/repos/#list-languages](https://developer.github.com/v3/repos/#list-languages)
I think ATM will do fine, but the back-end need some restructure for both maintainability and testing
=> Add repo languages

package.json, public/__test__/__snapshots__/script.test.js.snap, public/__test__/script.test.js, public/js/script.js
As discussed in #16 after the refactoring of the front-end JS I've added some tests using [Jest](https://facebook.github.io/jest/) 
The current code coverage is 75-80%
I've added NPM scripts as well:
test:  runs all the test suites (shortcut `npm t`)
test:watch: runs jest in watch mode,
test:coverage: runs jest with the code coverage flag,
test:updateSnapshot: runs jest and updates the stored snapshot,
test:full: runs jest in watch mode with the code coverage flag
once the back-end is refactored as well we can hook up jest to test all that as well
=> Frontend tests

public/js/script.js
Removing spaces around the username prevents a duplicate search bar from appearing if the user enters a query of two spaces.
=> Trim username

views/partials/prs.hbs
While using the checker on my mobile I noticed that the text detailing my pull request was spilling out of the container. I've increased the width of the container when viewed on a smaller device.
| ![Before](https://user-images.githubusercontent.com/6834105/31053475-ec0b3b16-a695-11e7-8f49-3980415cf51d.png) | ![After](https://user-images.githubusercontent.com/6834105/31053477-ee5ed698-a695-11e7-95af-2d631824ad3c.png) |
|:---:|:---:|
| Before | After |
=> Mobile styling

public/js/main.js
Before message "Username cannot be blank." was black and now it's white and following the same style as other errors.
=> Fixed style for empty user input

controllers/index.js, public/js/main.js, views/partials/prs.hbs
- https://github.com/jenkoian/hacktoberfest-checker/issues/140
This pull request will allow the web interface to show data about the user, which currently is only used for the avatar.
Previous method was by getting the avatar from the pull requests, but if none are found the user avatar would not be shown.
The `findPrs` function is now a bit more generalized by returning the prs and the user data as resolved promise parameters, rather than variables defined inside the request.
Some suggestions would be to generalize the `findPrs` even further by moving it out of the request (thus easing the load on the app each request) and possibly exporting it as well.
=> User avatar is now shown for people without PRs

controllers/index.js, views/partials/prs.hbs
Nothing in particular, just an enhancement. Searched a friend and tried to click their picture to get to their page, figured it was in the spirit of the event to make that happen.
(possibly https://github.com/jenkoian/hacktoberfest-checker/issues/128)
Adds a link to the searched user's github page to the their profile picture that appears after searching.
=> Add link to github.com/username on picture

.env.dist, .env.example, README.md
1. `.env.example` is more familiar than `.env.dist`
2. Since this file is copied and an `.env` file is created from it, there are quotes and comments that are not needed, so the quotes are removed, and the comments are raised above the variables, otherwise they will be in the variable GITHUB_TOKEN.
=> Refactor example env file

public/css/main.css, views/partials/prs.hbs
Changes: Add word break to PR item
Note: In `tachyons`, this property is removed.
Before | After
| - | -
=> Add word break to PR item

public/css/main.css, views/index.hbs
Changes: Pad username form down so that at 440px wide the check button isn't obscured by the "fork me on github" link
Before:
After:
=>  Move form input down a little bit so the check button isn't overlapped

.gitignore, Dockerfile, README.md
Changes: Use `yarn` in README and Docker, since it is mainly used and remove lock files in `.gitignore`.
=> Switch to Yarn

Dockerfile
Fixes issue #189
Changes:
* Use `node:6-alpine` as base image.
* Drop `npm install -g yarn` as `node:6-alpine` already provides it. ([Ref](https://github.com/nodejs/docker-node/blob/36585913a2776f7f72afcdbf0d39d54625716916/6.11/alpine/Dockerfile#L51-L67))
=> docker: use alpine, fix #189

controllers/index.js, views/partials/prs.hbs
Fixes issue #187 
Changes: Adds a isNotComplete boolean to the rendered payload and displays a link to the GitHub Hacktoberfest Issues page if not yet complete. 
=> Add link to hacktoberfest issues

views/index.hbs
Disables spellcheck on username field to avoid the annoying (and ugly) squiggly red line. Tested on chrome.
=> Disable spellcheck on username field

package.json, yarn.lock
In dotenv 2.0.0, it throws an error when `.env` file is not found, even if the env we wanted were already specified via shell.
```plain
$ GITHUB_TOKEN=xxxxxxxx node .
{ Error: ENOENT: no such file or directory, open '.env'
at Object.fs.openSync (fs.js:653:18)
at Object.fs.readFileSync (fs.js:554:33)
at Object.config (/home/xxx/hacktoberfest-checker/node_modules/dotenv/lib/main.js:30:37)
at Object.<anonymous> (/home/xxx/hacktoberfest-checker/index.js:15:8)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
at Function.Module.runMain (module.js:665:10) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
Express server listening on …
```
=> config: upgrade dotenv

public/css/stars.css
Fixes issue #213
Changes: Because of the `top` and `left` style prop of the `.stars-three` class it extends page layout size that looks like on the issue. Instead of removing the said prop. I added a `width` and `height` to compensate the excess size. Thus work on several screen size.
=> 3rd star background should blend on the section size

public/js/main.js
Fixes issue #235
Changes: Add closing brace to `name="username"` selector, so that WebKit no longer throws an exception ([the only browser to do so](https://www.reddit.com/r/firefox/comments/5nbmqi/on_handling_invalid_selector_strings:)).
Screenshots for the change: N/A
=> Fix broken selector in Webkit-based browsers

public/js/main.js
Fixes issue #242 
Changes: The jquery event handler for the `This is me button` was changed, so that it works when the button was not existing at page load.
That solves the problem described in the mentioned issue
This is not a visual change...
=> fix This is me button event handler

public/js/main.js, views/partials/prs.hbs
Changes: After searching for a username, there is an orange button "This is me", that when clicked, saves the username into local storage. I added the saveUser click handler to the http://hacktoberfestchecker.herokuapp.com/me so clicking on that link also saves the username to local storage.
I added this because I clicked on the http://hacktoberfestchecker.herokuapp.com/me link before I clicked on the "This is me" button and it didn't work (although I expected it to). I don't think this change will cause any negative reactions because just typing and going to http://hacktoberfestchecker.herokuapp.com/me doesn't have an affect.
Screenshots for the change: No visual changes
=> Also save user when clicking on /me link

controllers/index.js
Fixes issue #254.
Changes: 
- Set the option per_page to 100, to show PR amounts larger than 30.
=> Issue #254 - Correctly show PR amounts larger than 30

controllers/index.js, views/partials/prs.hbs
- use the current year, show last year's result before October 
- make background animation optional
This change removes the hardcoded year to search for PRs.
It also shows last year's result when checking before October.
The animation of the background (stars and clouds) is using a lot of CPU on the client machine.
The entire system becomes rather sluggish. This is not a great experience.
Animation is now off by default.
To activate it again, set the ENV variable ANIMATION to yes in the file .env
=> replace hardcoded year, show last year's result before October

views/partials/prs.hbs
Fixes issue #N/A
Changes: 
- Improved mobile styling
- Centered PR paragraph
Without 'tc' class
With 'tc' class
=> Added tc class to PR paragraph.

Dockerfile
Fixes issue #295 
Changes:
Fixed the node version by using `node: 8-apline` in the `Dockerfile`
=> Docker build: incorrect node version

views/partials/prs.hbs
`.o-0 glow` makes the avatar invisible to start. I've replaced it with `.dim` to make the avatar visible (and match the screenshots) while still having a reactive component.
This will also be fixed by #299 ([line number](https://github.com/jenkoian/hacktoberfest-checker/pull/299/files#diff-506a5a0ceb78b91144bb23a742b4c7f8R25)).
Before:
After:
=> Fix invisible avatar

.travis.yml
Fixes issue #312 
Changes: I've exchanged the usage of npm inside the `.travis.yml` so that travis is using yarn instead of npm.
=> Use yarn in travis instead of npm

README.md
Changes: Added a MIT license badge next to the Travis CI badge.
Badge obtained from https://shields.io/#/
=> added MIT license badge

Dockerfile
Files which will be copied to the `/app` directory in the docker image, are owned by `root`. They should be owned by the `octocat`, who will be used to start the server.
There are no usage changes.
No visible changes.
=> Copy files into image as user octocat

public/js/main.js, views/partials/prs.hbs
The twitter and fb share buttons use a hardcoded link.
This change uses the actual hostname (and path) of the checker web site.
=> remove hardcoded hostname (link) for share buttons

views/index.hbs
On an iOS device the mobile keyboard autocapitalises the first letter of your username and also tries to autocorrect any words. This is not ideal for GitHub user names.
This fix removes that and shows a lower case keyboard with no autocorrect.
- [Touch Keyboard Types](https://baymard.com/labs/touch-keyboard-types)
- [MDN HTML <form> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-autocapitalize)
=> Add 'autocapitalize' and 'autocorrect' attributes to the input

public/js/main.js
You can have a space in the name, and the page will work fine and load, but if you hit "this is me" it will save it with a space and then break.
=> Trim name input before storing in localstorage

src/pages/User/components/PullRequests/index.js
Fixes #340
**Ticket**: #340
This fixes the rendering of a `0` when there are no PRs.
=> Don't render number of PRs when count is 0

src/pages/User/components/PullRequests/UserInfo/ResultMessage/getResultMessage.js
Hacktoberfest 2019 requires only 4 PRs. Dashboard messages updated to reflect this.
=> fix(#357): update `getResultMessage` for 2019

src/pages/User/components/PullRequests/PullRequest/index.js
Hello! I opened issue #376 and I think I may found the problem. Patched it in this PR, hope everything is right.
When hacktoberfest label was present in PR, it was adding hacktoberfestp-4 to
div class. This PR fixes this by adding an extra space if 'hacktoberfest' label is present
fix #376
=> fix hacktoberfest label spacing

src/pages/User/components/PullRequests/UserInfo/PullRequestCount.js
Thanks for this website!
I noticed that the PR count is not centered (specially in mobile)
**Actual**:
**Result**:
=> feat: display PR count centered

src/pages/Faq/data.js
I've used Hacktoberfest Checker for several years now during Hacktoberfest and just found that they now offer a way you can see your progress on their own website. It made me as the question "Why is this project needed if Hacktoberfest's `Profile` now shows your progress?" so I thought I'd add that as a question to the new FAQ created under https://github.com/jenkoian/hacktoberfest-checker/issues/367
=> Added FAQ question about official "Profile" page showing progress

src/pages/Faq/components/FaqEntry.js
On the FAQ page, when viewing the page on mobile, text was flowing outside of its container. This commit resolves this issue.
**Before**
**After**
=> Fixed FAQ text overflow issue

src/pages/User/components/PullRequests/PullRequest/MergeStatus.js
I thought it may be a nice idea to make the status of each PR more obvious by adding some colour to the PR status icons.
**Screenshot:**
Thanks!
=> Colour PR status icons

src/components/Footer.js
There should be an equal footer margin for both top and bottom, as that will make it look better and balanced on pages where the content is taller than the page height. 
Scrolling to the bottom will make the FAQ button seem too close to the end of the page without the bottom margin.
Also fixed a typo where `class` should be `className` instead.
=> Improve website footer

api/controllers/pr/findPrs/index.js, api/controllers/pr/findPrs/loadPrs.js
According to FAQ, draft and spam pull requests should be ignored as well.
I tried `-label:invalid-label:spam` but it didn't work so I have to use `filter`.
=> Exclude draft and spam pull requests

api/controllers/pr/findPrs/index.js, package-lock.json, package.json, src/App.js, src/components/Footer.js, src/components/SiteTitle.js, src/pages/Faq/data.js, src/pages/User/components/PullRequests/LoadingIcon/index.js, src/pages/User/components/PullRequests/UserInfo/UserImage.js
I think that formatting the codebase is very important. I've seen the `.prettierrc` file, but some file didn't follow to the prettier standard.
Things that I did:
- Installed packages: husky (for running prettier before commit and push) and prettier-quick (faster write and fix through all staged files).
- Formatted all files that haven't been formatted.
- Removed `eslint` script in package.json because it makes other contributors confuse with actual Eslint.
- Added `--check` argument to the `prettier` script for format checking.
=> feat: add prettier husky hooks

.travis.yml
Changed `npm install` to `npm ci` to install dependencies based on lock file versions.
Changed `npm run eslint` to `npm run prettier` since `npm run eslint` was removed from package.json and was calling prettier to begin with.
=> [#440] Update travis config

src/components/RegisterReminder.js
So, because Hacktoberfest 2020 reward is choice (pick a T-shirt or plant a tree), I decided to add "or tree" on register reminder. I choose "or tree" in order to unite rhyme [tee or tree]
Sorry if my PR is not much commit
Thank you
=> Add "or tree" because Hacktoberfest 2020 reward can pick tee or plant a tree

api/controllers/pr/findPrs/index.js, src/pages/Faq/data.js, src/pages/User/components/PullRequests/PullRequest/PullRequestInfo.js, src/pages/User/components/PullRequests/PullRequest/index.js
Filters out PRs based on the [new rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update), implemented by digitalocean/hacktoberfest#596.
These new rules are only applied to PRs created after `2020-10-03T12:00:00.000Z`.
***
For all PRs created after the above date, their repos labels are fetched and a `repo_has_hacktoberfest_topic` property is added to the PR, representing if the PR repo has the `hacktoberfest` topic.
Then PRs that are created after the above date and their repo doesn't have the `hacktoberfest` topic are filtered out.
***
The pending time has been increased from 7 days to 14 days.
The `has_hacktoberfest_label` now represents if the `hacktoberfest-accepted` label is present, instead of the `hacktoberfest` label.
***
I haven't used Lodash in a while, so …
=> Filter PRs based on repo label

src/pages/User/components/PullRequests/ShareButtons.js
By having a space after the comma it was causing the tweet to read #
hacktoberfestchecker rather than #hacktoberfestchecker
=> Fix twitter hashtag

src/index.css, src/style.css
When I hover the register link on the top of the page, it looks like disappear because it's the same color as the background color.
Update with one of the light mode colors in tailwind config:
=> fix hover blue link on light mode

public/index.html
I noticed we were loading Press start twice but ignoring
space mono. The fallbacks are pretty close so it wasn't
noticable but hey it's worth trying to fix!
I swapped the existing method of loading the fonts to using
links instead which IMO is a bit simpler to use and doesn't
need us to download a javascript file before requesting the
css files to get our font
=> Fix google fonts not loading space mono

package.json
If this still doesn't work we could try and test `npx tailwindcss build -o src/index.css`
=> Attempt to fix tailwind-gen for Windows users.

README.md, src/components/Footer.js, src/components/RegisterReminder.js, src/pages/Faq/data.js
Replace outdated official Hacktoberfest URLs and linking to the new domain instead (https://hacktoberfest.com)
=> Update hacktoberfest official webpage link

src/components/UsernameForm/index.js
Possible solution to fix #709 
Do you think this solution is a little user hostile? 
Would it be better to apply the trim() method only onSubmit to all the usages of state `username` thereafter? 
Thank you.
=> bugfix: remove whitespaces from username input field

api/controllers/pr/findPrs/github/index.ts, api/controllers/pr/findPrs/gitlab/index.ts, src/pages/Faq/data.js
The review period is 7 days this year. See [here](https://hacktoberfest.com/participation/#pr-mr-details).
However the review period starts when a PR/MR is merged, approved, or labeled as "hacktoberfest-accepted". I don't know how to determine the review period is ended or not.
=> fix: Change back to 1 week review period

src/components/Navbar.js
Hey Ian, I have added subtle spans `<span>'|| '</span>` between the navbar components (NavLink) - Me, User, Compare with friends that space them out a little and give them the resemblance of separate navbar buttons.
=> UX Enhancement : Added spans between navbar components
